### ISSUE TITLE
Can't receive Submission in Mailhog

### ISSUE THREAD

**Issue by mortensassi** [agentejo/cockpit#1010]
Hi,

i'm trying to receive form submissions with mailhog but had no luck so far. Took a look at the [docs ](https://getcockpit.com/documentation/reference/configuration) but am not sure if i made the right config:

#### config.yml

```yml
mailer:
    from      : test@test.lo
    transport : smtp
    host      : localhost
    user      : test
    password  : 1234
    port      : 1025
    auth      : true
#    encryption: '' # '', 'ssl' or 'tls'
```

#### docker-compose.yml

```yml
mailhog:
    container_name: test_mailhog
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
```

**Comment by pauloamgomes** [comment]
Issue is probably on the user/password, you shoudlnt need that for mailhog, and the host should be the docker one and not localhost.

Below is working for me:

**config.yml**
```yaml
mailer:
  from: admin@cockpit.docker.localhost
  transport: smtp
  host: mailhog-cockpit
  port: 1025,
  auth: false,
  encryption: ""
```
**docker-compose.yml**
```yaml
  mailhog-cockpit:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.backend=cockpit-mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.cockpit.docker.localhost"
```

Note that I'm using traefik to access the mailhog ui.

**Comment by mortensassi** [comment]
Had no luck,

changed everything like config restarted docker-compose but with still can't receive the mails. 

The requests are visible in cockpit, so i guess it's still a config issue. Is traefik necessary? I'm able to access mailhog via 0.0.0.0:8025

**Comment by pauloamgomes** [comment]
No, traefik is only to access the traefik ui on port 80 (and remove the need to expose ports from the container).

I just reconfirmed and its working for my configurations, I have a cockpit form structure with an email populated in the Email field.

After the form is submitted and saved by cockpit I have the mail on mailhog:

![image](https://user-images.githubusercontent.com/102261/52636635-207cde00-2ec5-11e9-8cb2-c2d6d028f798.png)

**Comment by mortensassi** [comment]
Thank you for your reply, but still nothing. 
I've seen in your cockpit-react stack that you're using a php service, which uses Environments like:
`PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025` – 

do i need to implement this too in my file?

```yml
cms:
    container_name: test_cockpit
    image: "agentejo/cockpit"
    environment:
      COCKPIT_SESSION_NAME: test
      COCKPIT_SALT: DF601181-28E7-4A84-B32F-947FDE3C5FD8
    volumes:
      - ./www:/var/www/html
      - ./storage:/var/www/html/storage
      - ./config:/var/www/html/config
    ports:
      - '8420:80'
```

**Comment by pauloamgomes** [comment]
Sorry @mortensassi , I'm not using the official docker image from @aheinze , mine is based on wodby php:

```yaml
  php-cockpit:
    image: "wodby/php:7.3-dev-macos"
    container_name: "cockpit_php"
    depends_on:
      - mongo-cockpit
    environment:
      PHP_SENDMAIL_PATH: "/usr/sbin/sendmail -t -i -S mailhog-cockpit:1025"
      COLUMNS: 80
    volumes:
      - "../www:/var/www/html:cached"
```

the PHP_SENDMAIL_PATH seems to be the key here for communication between php container and mailhog
