### ISSUE TITLE
Unique Slugs Multilanguage

### ISSUE THREAD

**Issue by decodedesign** [agentejo/cockpit#1086]
Hi, really great work here!

I've been trying and failing to achieve multilanguage unique slugs.
I mean, if I have an entry title (in English) like "Test", I'd like that the slug "test" is generated, and if the title translation for the same entry is "Prueba" (in Spanish), the slug "prueba" for the translated title is generated as well.
But for every slug (source language or translation), if the same slug already exists, add a  "-$counter" appendix.

Cockpit core handles smoothly multilanguage slugs creation: 
-In a collection I configured "title" text field with {"slug":true} in configs, which is localized also.
-But it does not look for previously created slugs, if I have already saved an entry with the same title (in any of the languages).

Unique Slugs addon works great but only if "slug" field is not localized:
-The field "title" is configured as source for slug generation for a collection.
-This entry field ("title") is configured as localized in collection settings. 
-I created another field, named "slug", also localized.
-The addon looks for previous slugs, but only for the default title, and the "slug" localized field is empty for the translations.

Is there a way to achieve this?
Thank you very much for your awesome work!

**Comment by raffaelj** [comment]
@decodedesign I added the support for localized fields.

https://github.com/raffaelj/cockpit_UniqueSlugs/tree/localize

Can you test it, please? Than I'll pull it to the master branch. It worked on my local machine with the following setup:

config: 

```yaml
languages:
    de: Deutsch

unique_slugs:
    collections:
        # testlocale: title
        testlocale:
            - title     # type: text, localize: true
            - fallback  # type: text, localize: true
            - tags|0    # type: tags, localize: true
    localize:
        # testlocale: title
        testlocale:
            - title     # don't add the language postfix - "title" and not "title_de"
            - fallback
            - tags|0
```

If you omit the localize key, it should work like before.
