### ISSUE TITLE
How to get secret config values?

### ISSUE THREAD

**Issue by BlindDespair** [agentejo/cockpit#1256]
Hi, thank you for great csm, everything works great and I am loving it. But one question came to my mind when I configured smtp: how to tell cockpit to get secret values for config from a separate file or something? I am using a `config.yml` and I have it checked in my repository, then config folder is moutned to cockpit docker container with a volume. What I would like to avoid is having my username and password for smtp service in my repository even though it's private.
Here is an example:
```
  mailer:
    from: {myMail}
    transport: smtp
    host: {myHost}
    user: {myUser}
    password: {myPassword}
    port: 25
    auth: true
    encryption: tls
```
I wouldn't even mind having this whole block in a separate file if cockpit could somehow include it in the main config. Some help or advice will be appreciated.

**Comment by aheinze** [comment]
use `config.php` instead of `config.yml` 

```
<?php

return [
    "mailer" => [
        "from" => getenv('MAILER_FROM'),
        "password" => getenv('MAILER_PASSWORD'),
        .
        .
        .
    ]
];
```

**Comment by BlindDespair** [comment]
@aheinze Thanks for response. Can I read somewhere about this `getenv`? How does it work? Where can I set it? Thing is that I am not a php developer and sometimes it's hard for me to follow it. For me it would be better if there was a feature like:
```
mailer:
    from: $MAILER_FROM
    transport: smtp
    host: $MAILER_HOST
    user: $MAILER_USER
    password: $MAILER_PASSWORD
    port: 25
    auth: true
    encryption: tls
```
So that I could keep my config rather declarative and not write custom logic in it. But I can go with this `getenv` stuff too, question is where do I set those environment variables? Just on system with `export` or is there a file I could create? I am running it in docker so it is tricky to pass env variables through docker-compose file. If it can be a file that I can just volume, it would be way easier.

**Comment by raffaelj** [comment]
> If it can be a file that I can just volume, it would be way easier.

You can overwrite the mailer service with your own config with this snippet in your `/config/bootstrap.php`

```php
// path to your mailer config file
$mailerConfigPath = '/path/to/mailer.yaml';

// parse config file
$options = Spyc::YAMLLoad($mailerConfigPath);

// use different parser...
// $options = parse_ini_file('/path/to/mailer_config.ini');

$app->service('mailer', function() use($options){
    $mailer = new \Mailer($options['transport'] ?? 'mail', $options);
    return $mailer;
});
```

Content of your `mailer.yaml`:

```yaml
from      : 
from_name : 
transport : smtp
host      : 
user      : 
password  : 
port      : 587
auth      : true
encryption: tls
```
