### ISSUE TITLE
/authUser response doesn't contain "api_key" for any user except admin.

### ISSUE THREAD

**Issue by entelostre** [agentejo/cockpit#1378]
From my frontend, I create a user by posting to /saveUser successfully but when I log in by posting to /authUser the response json is missing the "api_key" property. Any clues why?

**/authUser json response:**

```
active: true
email: "asd@asd.com"
group: "user"
i18n: "en"
name: "test"
user: "test"
_created: 1606895159
_id: "5fc7463735393422d8000210"
_modified: 1606895159
```

When I use the cockpit admin credentials to login, "api_key" property is indeed in the response.

**Here is my config.yaml**

```
# Cockpit settings
groups:
    user:
      $admin: false
      $vars:
        finder.path: /storage/upload
        media.path : /storage/media
        finder.allowed_uploads: png, jpg, jpeg
        assets.allowed_uploads: png, jpg, jpeg
      cockpit:
        backend: false
```
