### ISSUE TITLE
Is there a way to restrict assets folder per group?

### ISSUE THREAD

**Issue by silvester-pari** [agentejo/cockpit#1492]
Hello all, Cockpit is great so far!
The only thing I am struggling with is setting a root for the assets manager - since we are managing multiple groups in the CMS it is crucial that each group sees only the own assets. Is this even possible?

### setting the finder.path
```
groups:
  testgroup:
    cockpit:
      accounts: false
      backend: true
      finder: true
    $vars:
      finder.path: /storage/uploads/testgroup/
```
This works to restrict the finder starting location, but not the assetsmanager folder

### setting media.path
```
groups:
  testgroup:
    cockpit:
      accounts: false
      backend: true
      finder: true
    $vars:
      media.path: /storage/uploads/testgroup/
      <or>
      media.path: /testgroup/
```
I found this digging in some older issues (e.g. https://github.com/agentejo/cockpit/issues/72) but this seems to be changed in the newer versions

### disabling assetsmanager completely
```
groups:
  testgroup:
    cockpit:
      accounts: false
      backend: true
      finder: true
      assetsmanager: false
      <or>
      assets: false
      <or>
      media: false
```
This does nothing.

Is there any way to achieve this? Either disabling assets completely, or setting a starting folder.
Any help is much appreciated! Thanks
