### ISSUE TITLE
Can't log in with custom user groups

### ISSUE THREAD

**Issue by Blemming** [agentejo/cockpit#563]
I made a custom user group with the config YAML:
```
groups:
    contenteditor:
        collections:
            create: false
            delete: false
```
I see the group in the user page. But when I set a user to the group, the user can no longer login.
I'm using Cockpit Next plugged into a mongo Database. I don't if this is a bug or I am missing something.

**Comment by aheinze** [comment]
You need to add access right for the cockpit backend

```
groups:
    contenteditor:
        cockpit:
            backend: true
            finder: true
        collections:
            create: false
            delete: false
```
