### ISSUE TITLE
Is it possible to prevent a particular user group from creating new user accounts?

### ISSUE THREAD

**Issue by jrlmontejo** [agentejo/cockpit#567]
This is my current `config.yaml`:
```
# Cockpit settings

groups:
  editor:
    $admin: true
    $vars:
      finder.path: "admin/storage/uploads"'
```

I want the `editor` group to have the same read/write access as `admin`, except creating new user accounts.

**Comment by jrlmontejo** [comment]
After checking the code, I found the correct config:
```
groups:
  editor:
    $admin: false
    $vars:
      finder.path: "admin/storage/uploads"
    cockpit:
      accounts: false
```
