### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by frankglv** [agentejo/cockpit#602]
Hi,

I love the cockpit concept but cannot really find a way to configure MongoDb with username/password auth. The documentation is basically zero on this.

I tried something like this with no luck:

```
database:    
    server: mongodb://username:password@ipaddress:27017/
    options:
        db: dbname
```

I copied the sqlite "accounts" data into an "accounts" collection in Mongo.
No success either. Cockpit does not log until I remove these lines from the config file (that is, restoring SQlite).

Any help?
Thanks

**Comment by aheinze** [comment]
did you after switching to mongodb open/run `/install` in the browser?

**Comment by frankglv** [comment]
Yes, but it autodirects to the login page. Is this unexpected?
Do you have any sort of material/document I can skim to get some ideas?
Thanks

2017-11-22 15:02 GMT+01:00 Artur <notifications@github.com>:

**Comment by yllumi** [comment]
Hi all,
I also get the same problem when I update config.yaml by adding these line:
```
database:
  server: mongodb://localhost:27017
  options:
    db: cockpitdb
```
The browser shows error 500. I have try to add these line before and after run /install.
I have install mongodb on localhost, PHP 7.1 and nginx.

**Comment by yllumi** [comment]
Hi @frankglv, I have solve this problem. If you got same situation like I described above, it is because PHP extension for MongoDB is not installed. You can see this page to install MongoDB PHP Driver http://php.net/manual/en/mongodb.installation.pecl.php

And I think Cockpit must describe about this issue in documentation.

**Comment by hyperpress** [comment]
If anyone has a working example of how to connect to MongoDB 3.6.3 with config.yaml I would really appreciate it. I installed the mongodb pecl extension, enabled it, and restarted php7.2-fpm and apache2 without issue.

I've tried a couple of config variations of this in config.yaml:
```
# use mongodb as main data storage
database:
    server: mongodb://username:password@localhost:27017
    options:
        db: cockpit
```
and this:
```
# use mongodb as main data storage
database:
    server: mongodb://localhost:27017
    options:
        db: cockpit
    auth:
        username: cockpit
        password: Cb0CzQwSa8yzQ5f
```
Both both throw the following fatal error:
`
[Tue Mar 20 00:49:53.925658 2018] [proxy_fcgi:error] [pid 7558:tid 139978638071552] [client 192.168.1.45:44694] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MongoDB\\Driver\\Exception\\RuntimeException: there are no users authenticated in /var/www/html/cockpit/lib/MongoDB/Operation/InsertOne.php:106\nStack trace:\n#0 /var/www/html/cockpit/lib/MongoDB/Operation/InsertOne.php(106): MongoDB\\Driver\\Server->executeBulkWrite('cockpit.cockpit...', Object(MongoDB\\Driver\\BulkWrite), Object(MongoDB\\Driver\\WriteConcern))\n#1 /var/www/html/cockpit/lib/MongoDB/Collection.php(751): MongoDB\\Operation\\InsertOne->execute(Object(MongoDB\\Driver\\Server))\n#2 /var/www/html/cockpit/lib/MongoHybrid/Mongo.php(102): MongoDB\\Collection->insertOne(Array)\n#3 /var/www/html/cockpit/lib/MongoHybrid/Client.php(40): MongoHybrid\\Mongo->insert('cockpit/account...', Array)\n#4 /var/www/html/cockpit/install/index.php(63): MongoHybrid\\Client->insert('cockpit/account...', Array)\n#5 {main}\n  thrown in /var/www/html/cockpit/lib/MongoDB/Operation/InsertOne.php on line 106\n
`
I want to use MongoDB because the project needs a more robust DB than sqlite3. So, grateful for any help you can provide. Thanks very much.

**Comment by cguillou** [comment]
@frankglv After experiencing the same issue, I dig into the doc and found the problem. The database name is required if you specify the username/password in the server URI. Otherwise, Mongo try to connect to the admin database.

So just adding the database name at the end like this should solve your problem.

```
database:    
    server: mongodb://username:password@ipaddress:27017/dbname
    options:
        db: dbname
```

And don't forget to redo the `/install`

Link to doc: https://docs.mongodb.com/manual/reference/connection-string/
