### ISSUE TITLE
finder - listing files in upper folder

### ISSUE THREAD

**Issue by moabi** [agentejo/cockpit#706]
the getcockpit finder seems to be able to go to a upper folder where it is located, therefore users (with admin rights) can delete files they should not see...and delete it also.

*(re)define admin group ?*
```
groups:
    admin:
        $admin: true
        $vars:
            finder.path: /storage/upload
        cockpit:
            backend: true
            finder: true
```

does not seems to work

**Comment by raffaelj** [comment]
Do you use cockpit in a subfolder? Try:

```yaml
groups:
    admin:
        $admin: true
        $vars:
            finder.path: /cockpit/storage/uploads
```

My finder points to the upload folder now.

But if I set `finder.path`, `config.yaml` becomes unavailable in system settings - strange... I had to change it back via text editor.

Setup:
* next branch, Xampp7, PHP7, Apache
* `http://localhost/cockpit/settings/edit`
* `E:/xampp7/htdocs/cockpit` is a symlink to `E:\github\cockpit`

![no-config-file](https://user-images.githubusercontent.com/13042193/43049105-7da12c54-8df2-11e8-986c-efb48444ebfc.png)

**Comment by moabi** [comment]
Cockpit is used in a subfolder.
I did set up the config this way too
```
groups:
    admin:
        $admin: true
        $vars:
            finder.path: /static/storage/uploads
```
and the system is back to normal, but restricting the rights in the config file does not seems to be a secure way to do it. As the application can still access a upper folder. On version 5.x and previous, the application did not mind if the rights were restricted, but I upgraded to 6.x and now it gives an error 500 if the application does not have the rights.

Any way to define it elsewhere ? @aheinze  ?
