### ISSUE TITLE
Missing env variables for cockpit/mongo 

### ISSUE THREAD

**Issue by elizasj** [agentejo/cockpit#708]
Currently the  [cockpitcms/cockpit README ](https://github.com/COCOPi/cockpit-docker/blob/master/README.md) as well as the [cockpit docs](https://getcockpit.com/documentation/api) themselves lack information about how you can pair the docker image with mongodb, including the environment variables needed. I had to dig through the  [docker-compose.yml](https://github.com/COCOPi/cockpit-docker/blob/master/docker-compose.yml) file of the image’s maintenance repo (which was pretty hard to find because of #707 ) in order to get my hands on this information.

```
COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: 
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
```

Could be a good idea to add some documentation to the README and to the website’s docs about how to pair with mongodb and what variables can be set, since you do advertise the docker image on the site, and the rest of your docs are so clear.

**Comment by elizasj** [comment]
If you're using docker-compose you would run your docker containers (cockpit & mongo) with a `docker-compose up` command. 

I think you'd also need to create a network bridge so your mongo & cockpit containers can find each other. Consider defining a volume  to contain the data you’ll want to serve out to the mongodb container every time you boot up your system too.

To create your volume: 

`docker volume create --name whatever-you-want-to-name-your-volume` 

And then your docker compose file would be something like :

```
//docker-compose.yml
version: '2'
services:
  mongo:
    image: 'mongo'
    volumes:
      - 'mongo-vol:/data/db'
    networks:
      - yournetworkbridge
  master:
    image: 'aheinze/cockpit'
    ports:
      - "8080:80"
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: "y283y2983y48239y"
      COCKPIT_DATABASE_SERVER: "mongodb://<dbuser>:<dbpassword>@dsXXXXX.mlab.com:55539"
     COCKPIT_DATABASE_NAME: "cockpitdb"
    depends_on:
      - mongo
    networks:
      - yournetworkbridge
networks:
  yournetworkbridge:
    driver: bridge
volumes:
  mongo-vol: null
```
