### ISSUE TITLE
Custom fields for users

### ISSUE THREAD

**Issue by NaderIkladiousC** [agentejo/cockpit#736]
What is the proper way for adding custom fields for users as adding for the collection.

**Comment by NaderIkladiousC** [comment]
on Reading some of the code

I found that I can edit accounts fields thought the `config.yaml` file.
but yet I couldn't find the syntax to create new field.

```yaml
account:
  fields:
    birthDate: Date
```

Thanks in advance.

**Comment by gryphonmyers** [comment]
Are you asking how to add fields to a collection that are only visible to a specific user or user class?

**Comment by NaderIkladiousC** [comment]
Thanks for your response

I just wanted to add normal fields for the normal user.

and figured the way by reading through the core files

`adding this in config.yml`
```
yml
account:
  fields:
    country:
      label: County
      type: collectionlink
      options:
        link: countries
        multiple: false
    city:
      label: City
      type: collectionlink
      options:
        link: cities
        multiple: false
    area:
      label: Area
      type: collectionlink
      options:
        link: areas
        multiple: false
    birthDate:
      label: Birth Date
      type: date
      options:
        format: 'YYYY/MM/DD'
    interests:
      label: Intersts
      type: collectionlink
      options:
        link: interests
        multiple: true
    image:
      label: Image
      type: image
```

would it be possible to add fields for a user with a specific role?

Thanks very much
