### ISSUE TITLE
Docker Mongo ENV Variables not being used

### ISSUE THREAD

**Issue by joshmeads** [agentejo/cockpit#776]
When you pass the following to docker as ENV it doesn't seem to actually use them.

```
COCKPIT_SESSION_NAME: cockpit
COCKPIT_SALT: <generated>
COCKPIT_DATABASE_SERVER: mongodb://<user>:<pass>@<host>:<port>/<authdb>
COCKPIT_DATABASE_NAME: cockpit
```

Trying to connect to a remote mongo instance. The user has permissions on the DB "cockpit" and correct security groups in AWS to allow the docker server (ECS via EC2) to reach the mongo server.

After `/install` and logging in, any new accounts, post creations, nothing appears in Mongo.

Does the above only work if you're using docker compose with a network interface version of mongo?

After I exec into the docker container, running `printenv` shows the correct variables.

What is the recommended way to run Cockpit in a production environment?

**Update**:
Also doesn't work with the following docker-compose file locally:
```
version: '3'
services:
  cms:
    image: agentejo/cockpit
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: B81376D0-607C-46C4-BF57-1B6C97632546
      COCKPIT_DATABASE_SERVER: 'mongodb://host.docker.internal:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
    ports:
      - "8080:80"
```

It does however work if I edit the settings => config. However that is somewhat pointless as if the image restarts, you'll lose that configuration.

**Comment by ChaoLiangSuper** [comment]
@joshmeads  Hey, mate. check this new doc file. It works for me. 
The problem seems to be those ENV settings are not used internally.

https://github.com/woutervddn/cockpit-docs/blob/b52ec6d63c0627b3c27180df109f93e0077927c3/reference/docker/index.md

**Comment by Rozkalns** [comment]
@joshmeads You have to assign host volume for the `/var/www/html/config` therefore config.yaml will be kept in safe place on your disk.

**Comment by jaredjensen** [comment]
I couldn't get the custom config.php file to take effect, either.  Instead, I created a config.yaml file with the mongo settings and updated my Dockerfile to copy it:

```
FROM agentejo/cockpit
COPY config.yaml /var/www/html/config/config.yaml
```

Then I rebuilt my Docker image, restarted the container, and hit the /install endpoint.  After that, I was able to log in, create a collection, create an entry, and see that in the mongo db.

**Comment by filipburian** [comment]
@jaredjensen Could you show me example config.yaml file? I got same issue, and it looks like it could help.

**Comment by filipburian** [comment]
@jaredjensen Thank you. My .yaml looks a little bit different. I got no app.name and sec-key.

```
- database:
    server: mongodb://user:password@ds281163.mlab.com:33356
    options:
      db: cms_name
```
In my dockerfile I use only 3 commands, also I am not using docker-compose.yml ENV variables.
```
FROM agentejo/cockpit
EXPOSE 80
COPY config.yaml /var/www/html/config/config.yaml
```
Do you think that parts which I am missing my cause the problem? (Sec-Key, app-name)
I also noticed that in your yaml "database" is declared without "-" which is required to be an array.

**Comment by jaredjensen** [comment]
I'm not specifying the db name in the server URL, so try without that.  I suspect changing `- database` to `database` (removing the dash) made it work for you.

I solved the persistence issue by using persistent external volumes for both the Mongo data and the Cockpit storage folder in my docker-compose.yml.  The relevant parts are:

```
version: '3.5'
services:
  db:
    container_name: pyd_db
    image: mongo:4.0.2
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: pyd_mongodb_data
        target: /data/db
  cms:
    container_name: pyd_cms
    image: pyd/cms:local
    build:
      context: ./cms/docker
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8203:80'
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: ${COCKPIT_SALT}
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: pyd_cms
    volumes:
      - type: volume
        source: pyd_cockpit_data
        target: /var/www/html/storage

volumes:
  pyd_cockpit_data:
    external: true
  pyd_mongodb_data:
    external: true
```
