### ISSUE TITLE
How to send mail with the form API ?

### ISSUE THREAD

**Issue by Jeyffrey** [agentejo/cockpit#827]
Hi, I'm trying to send mail on form submit with the cockpit API.

I'm using this code : https://github.com/agentejo/cockpit/issues/638#issuecomment-366411145, but it only save the data in the back-office. It doesn't send any mail.

If you have a solution, can you explain me how to do ? :)

**Comment by raffaelj** [comment]
You have to add a mail address in your form settings to receive mails and you have to setup your SMTP configuration in config/config.yaml, too. Otherwise Cockpit doesn't know, how to send mails.

Adjust the settings to your needs.

```yaml
# use smtp to send emails
mailer:
    from      : contactform@example.com
    transport : smtp
    host      : smtphost.provider.com
    user      : fancy-username
    password  : SuperSavePassword
    port      : 587
    auth      : true
    encryption: starttls
```
