### ISSUE TITLE
Security - uploading executable files with finder and assets manager

### ISSUE THREAD

**Issue by raffaelj** [agentejo/cockpit#839]
While testing https://github.com/agentejo/cockpit/issues/706#issuecomment-413164374 I discovered an easy way to manipulate files as non-admin by uploading a php file with the finder or the assets manager and calling the file afterwards. This is a big security hole for uses cases, where someone is allowed to upload images etc.

Is there a way to restrict file types for uploads and I just missed the option?

And restricting file types might work for the assets manager when the finder is disabled. Otherwise a file called logo.png could easily be renamed to evilcode.php with the finder.

**Comment by aheinze** [comment]
just landed in next branch: https://github.com/agentejo/cockpit/commit/8fe10aec79df1fa4ac78e934b79b1fedb09b86ea

you can now define allowed file types for finder + assets:

via global setting:

```
allowed_uploads: pdf, png, jpg, zip
```

or for each user group:

```
groups:
    author:
        $admin: false
        $vars:
            finder.path: /storage/upload
            finder.allowed_uploads: pdf, png, jpg
            assets.allowed_uploads: png, jpg
```
