### ISSUE TITLE
REST Access via header token.

### ISSUE THREAD

**Issue by Johannestegner** [agentejo/cockpit#852]
Been looking a lot in the documentation and code for a way to not use a query parameter for API token authentication. Looking in the code ( https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/rest-api.php#L22 ) it looks like it should be possible to use the `HTTP_COCKPIT_TOKEN` header instead of the query parameter, all good! But when using the header, a CORS error occurs due to the header not being in the `accepter-headers` header (https://github.com/agentejo/cockpit/blob/next/index.php#L27).

Iv'e tried to change the configuration of the cockpit installation to no avail, it does not seem to load correctly. The file is created and I can see changes made to stuff like the application name, but the accepted header list is not loaded.

There is no documentation about this (the token through header, other type of authentication headers etc etc, nor the accept-headers list in the config). Any pointers?

An alternative to the token header would be to use the (already accepted) `Authentication` header instead. But that header does not seem to be used anywhere in the code from my research.

**Comment by aheinze** [comment]
Hi,

can you post you configuration her?

Thanks!

**Comment by Johannestegner** [comment]
Well, I have tried a lot of different configurations, the one that I find most reasonable is the following:

```yaml
# Cockpit settings
app.name: JustToTestThatConfigActuallyWorks!
cors:
  allowedHeaders: '<extra headers here...>, X-Requested-With, Content-Type, Origin, Cache-Control, Pragma, Authorization, Accept, Accept-Encoding'
```

I will try to get the person hosting the cockpit installation to update to the latest `next` version for the Bearer token implementation, thank you for swift response! :)
