### ISSUE TITLE
Mailer Config is not working, from, from_name have no effect

### ISSUE THREAD

**Issue by crtl** [agentejo/cockpit#891]
Hi,
it is not possible to properly configure the mailer.
Everytime I try to send an email it is sent with an from address of `root@localhost` which is not valid and despite I configured a diffrent `from` and `from_name` in my `config.yaml`.
An additional problem is, when using the `\Mailer` class instead of `\PHPMailer\PHPMailer\PHPMailer` it is not possible to properly handle errors. You then have to use `\Mailer::createMessage` to get access to the `PHPMailer` instance to access `PHPMailer::$ErrorInfo`. 
But then again when using `\Mailer::createMessage` you have to manually pass the options.

So the mailing in general is a bit bulky and should be refactored.

**Comment by raffaelj** [comment]
Can you explain, what you did before and which version you use?

Maybe... Do you use a mail address with special chars like German umlauts (e. g. "ö" is valid in urls, but `filter_var('bob@exömple.com', FILTER_VALIDATE_EMAIL)` says false?

I see the problem with the error handling too. This is a problem, especially when forms are configured to not store data and the mailer fails.

**Comment by crtl** [comment]
Ive changed my config.yaml by adding my mail credentials:

```yaml
mailer:
  from      : ****
  from_name : ****
  reply_to  : ****
  transport : smtp
  host      : smtp.strato.de
  user      : ****
  password  : "****"
  port      : 465
  auth      : true
  encryption: 'ssl'
```

It has nothing to do with the E-Mail-Address etc. and I have no "Umlaute" anywhere.
The config values are present when I `var_dump($this->config);` somewhere in the app.
