### ISSUE TITLE
SSL/TLS connection to MongoDB

### ISSUE THREAD

**Issue by hellmaca** [agentejo/cockpit#914]
I need to enter driverOptions in order to connect to my MongoDB in dev. I see these two files as the place where I might be able to add them in manually:

cockpit/lib/MongoHybrid/Mongo.php
cockpit/lib/vendor/mongodb/mongodb/src/Client.php

I just need to add the following options, but I am at a loss as to where to specify them:

pem_file
pem_pwd
ca_file

Any help or direction is much appreciated.

**Comment by aheinze** [comment]
Wit this commit https://github.com/agentejo/cockpit/commit/85798a41ede7a781badeaadfbfebb78589718524 you should now be able to define custom driver options:

```
database:    
    server: mongodb://localhost:27017
    options:
        db: cockpitdb
    driverOptions:
        ca_file: '...'
```

please try the current next branch
