### ISSUE TITLE
Updating to 0.8.6 with mongodb

### ISSUE THREAD

**Issue by Blemming** [agentejo/cockpit#948]
I'm trying to update my 0.5.3 to 0.8.6, everything is dandy until I add the config.yaml with my database configuration. I get an error 500

Here is my config.yaml

```
# Cockpit settings
languages:
    fr: French
database:    
    server: mongodb://localhost:27017
    options:
        db: cockpitbeaulieudb
```

my apache error log gives me : 

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to MongoDB\\Driver\\Server::executeQuery() must be an instance of **MongoDB\\Driver\\ReadPreference
```

I'm using php 7.2 and mongodb 1.5.3 installed with pecl

Any ideas ?
