### ISSUE TITLE
MongoDB config fatal error

### ISSUE THREAD

**Issue by flinbu** [agentejo/cockpit#959]
Hi, thanks for cockpit!

I have the next issue when move to mongodb and try to run install again:
`Fatal error: Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No servers yet eligible for rescan in /var/www/html/lib/vendor/mongodb/mongodb/src/Collection.php:797 Stack trace: #0 /var/www/html/lib/vendor/mongodb/mongodb/src/Collection.php(797): MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference)) #1 /var/www/html/lib/MongoHybrid/Mongo.php(104): MongoDB\Collection->insertOne(Array) #2 /var/www/html/lib/MongoHybrid/Client.php(40): MongoHybrid\Mongo->insert('cockpit/account...', Array) #3 /var/www/html/install/index.php(68): MongoHybrid\Client->insert('cockpit/account...', Array) #4 {main} thrown in /var/www/html/lib/vendor/mongodb/mongodb/src/Collection.php on line 797`

I try config.yaml in this ways:
```
database:
    server: mongodb://localhost:27017
    options:
        db: dbname
```
This:
```
database:
    server: mongodb://username:password@localhost:27017/dbname
    options:
       db: dbname
```
This one too:
```
database:
    server: mongodb://localhost:27017
    options:
       db: dbname
       username: username
       password: password
```

But always get the same error.

I'm using Apache server on DigitalOcean, mongo, php-mongo is installed and running.
DB is created and user is created and assigned to db
```
MongoDB shell version: 3.2.21
connecting to: localhost:27017/test
{
        "ismaster" : true,
        "maxBsonObjectSize" : 16777216,
        "maxMessageSizeBytes" : 48000000,
        "maxWriteBatchSize" : 1000,
        "localTime" : ISODate("2018-12-20T03:57:10.220Z"),
        "maxWireVersion" : 4,
        "minWireVersion" : 0,
        "ok" : 1
}
```
In spite of everything, it still does not work.

Thanks!

PD: SSL is enabled on server and I try passing `ssl: true`

Actually, I try all in #602 with no success
