### ISSUE TITLE
mongo fatal error on collections 

### ISSUE THREAD

**Issue by AKApumkin** [agentejo/cockpit#967]
When using integers on the name, group and label fields, 
e.g. 1, 2, 3
it causes the following error:

Oh no! Something went terribly wrong:
Call to a member function fetch() on boolean

The only way to restore is a clean wipe.

**Comment by pauloamgomes** [comment]
Hey @AKApumkin , can you detail better the issue? You mean inserting only a number in a collection type (field name, group or label)?
It seems to work well on next branch!

**Comment by AKApumkin** [comment]
![collection](https://user-images.githubusercontent.com/13747102/50894578-839ad100-143e-11e9-9cb2-31cd12dead11.png)
![db_error](https://user-images.githubusercontent.com/13747102/50894579-84336780-143e-11e9-9124-ed8fbece4457.png)

**Comment by AKApumkin** [comment]
Looks like that might be the issue with Mongo, im using the latest from docker, i have attached my docker-compose.yml

separately i managed to fix it by adding a pattern to the view on those fields that prohibits 0-9. However i'm still trying to figure out how the persistent data from the cockpit container can be stored in a volumes, so in the event of a restart, this fix and all subsequent changes are persistent. 

```
version: '3'
services:
  db:
    image: 'mongo:latest'
    volumes:
      - './mongo-vol:/data/db'
    networks:
      - my_net
  cms:
    image: agentejo/cockpit
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: C23132asdSDa93
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: my_db
    depends_on:
      - db
    ports: 
      - "8080:80"
    networks:
      - my_net
networks:
  my_net:
    driver: bridge


```
